### ISSUE TITLE
Is it really GPT4

### ISSUE THREAD

**Issue by tim-gromeyer** [hillis/gpt-4-chat-ui#1]
Good day,

I was interested in a GPT4 GUI and came across this project. It looks really nice but if I ask it if it's GPT4 it says no. Take a look for yourself:

![ChatGPT](https://user-images.githubusercontent.com/58736434/228647077-f43a8cad-faa6-4a5b-ac0e-e3c7a6cab775.png)

And yes, I have acces to GPT4:

![GPT4 access](https://user-images.githubusercontent.com/58736434/228647371-9a388481-4162-41a7-a4cd-aab89f5dca88.png)

**Comment by hillis** [comment]
I have had the same issue but when looking at my API usage it is pulling from the GPT-4 model.  I know when I ask ChatGPT it will answer correctly but not sure why the GPT-4 api direct from OpenAI is not.  I have also tested this in the OpenAI playground and get the same answer.

**Comment by tim-gromeyer** [comment]
Hmm ... when I look at the API usage, it actually shows GPT-4.

So it looks like it is a problem on the OpenAi side. That's why I'm closing this issue. But thanks for your help!
