### ISSUE TITLE
Got error on first use

### ISSUE THREAD

**Issue by MajorLettuce** [hillis/gpt-4-chat-ui#2]
I've created `.env.local` with my API key and ran it using `npm run dev`

On my first prompt I got this error in the UI:

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

**Comment by quartzar** [comment]
I have encountered the same issue.

[Here](https://pastebin.com/4iWYfQEX) is a pastebin of the terminal output. Note my API key has been removed, hence `<key redacted>`.

**Comment by hillis** [comment]
Make sure you have access to GPT-4 API.  If you do not go to makechain.ts and comment out modelName or change it to gpt-3.5-turbo.  Also try Remove the .local and just use .env
